name: tcpdump-jdstrand
summary: tcpdump for Ubuntu Core
version: 4.9.3-4+snap1
license: BSD-3-Clause
description: |
 tcpdump for Ubuntu Core
grade: stable
confinement: strict
base: core20
architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf
- build-on: ppc64el
- build-on: s390x

system-usernames:
  snap_daemon: shared

apps:
  tcpdump:
    # -Z snap_daemon works but if specify -Z root is looks weird in ps
    # even though it ends up running as root. Perhaps update wrapper?
    command: usr/sbin/tcpdump -Z snap_daemon
    environment:
      LD_PRELOAD: "$SNAP/wraplib.so"
    plugs:
    - bluetooth-control
    - firewall-control
    - network-control
    - hardware-observe
    - home
    - removable-media

parts:
  tcpdump:
    plugin: make
    source: ./src
    build-packages:
    - build-essential
    stage-packages:
    - libpcap0.8
    - tcpdump
    stage:
    - -etc
    - -lib*
    - -usr/lib/*/audit
    - -usr/lib/*/engines*
    - -usr/lib/*/gconv
    - -usr/lib/*/libcrypto*
    - -usr/lib/*/libssl*
    - -usr/share/doc
    - -usr/share/lintian
