name: tcpdump
summary: Command-line network traffic analyzer
version: 4.9.3-4ubuntu0.1+snap1
license: BSD-3-Clause
description: |
 This program allows you to dump the traffic on a network. tcpdump is able to
 examine IPv4, ICMPv4, IPv6, ICMPv6, UDP, TCP, SNMP, AFS BGP, RIP, PIM, DVMRP,
 IGMP, SMB, OSPF, NFS and many other packet types.
 .
 It can be used to print out the headers of packets on a network interface,
 filter packets that match a certain expression. You can use this tool to track
 down network problems, to detect attacks or to monitor network activities.
grade: stable
confinement: strict
base: core20
architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf
- build-on: ppc64el
- build-on: s390x

assumes:
- command-chain

system-usernames:
  snap_daemon: shared

slots:
  captures:
    interface: content
    write:
    - $SNAP_COMMON/captures

hooks:
  install:
    plugs: []

apps:
  tcpdump:
    command: usr/sbin/tcpdump
    command-chain:
    - bin/set-user  # -Z snap_daemon
    environment:
      # setuid(snap_daemon), setgid(snap_daemon) and setgroups(0, NULL)
      LD_PRELOAD: "$SNAP/wraplib.so"
    plugs:
    - bluetooth-control
    - firewall-control
    - network-control
    - hardware-observe
    - home
    - removable-media

parts:
  tcpdump:
    plugin: make
    source: ./src
    build-packages:
    - build-essential
    stage-packages:
    - libpcap0.8
    - tcpdump
    stage:
    - -etc
    - -lib*
    - -usr/lib/*/audit
    - -usr/lib/*/engines*
    - -usr/lib/*/gconv
    - -usr/lib/*/libcrypto*
    - -usr/lib/*/libssl*
    - -usr/share/doc
    - -usr/share/lintian
  dumper:
    plugin: dump
    source: files/
